### ISSUE TITLE
Connection Failed

### ISSUE THREAD

**Issue by G6EJD** [bimmerconnected/ha_custom_component#77] opened 2024-08-23 07:43 UTC
Was working, but in the last day it looks like BMW has changed their address for this data, comes up with HTTPS address error, integration can no longer be added.

**Comment by JasperSolo** [comment] 2024-08-24 08:44
exactly the same problem.😒

**Comment by rikroe** [comment] 2024-08-24 14:54
Duplicate of https://github.com/home-assistant/core/issues/124464. 

tl;dr: If you have the QuotaError, **disable** the integration and retry **after 0:00 UTC**.

**Closed by rikroe** 2024-08-24 14:54 UTC
